.gitignore
Gemfile
Gemfile.lock
config/routes.rb

heroku-git-cloudinary-routes

---

app/controllers/clients_controller.rb

client show

---

Gemfile
Gemfile.lock

cloudinary fix

---

app/controllers/clients_controller.rb
app/views/clients/edit.html.erb
db/seeds.rb

edit-update-client

---

app/controllers/clients_controller.rb
app/models/client.rb

validation-client-not-working

---

db/seeds.rb

booking-seed

---

app/controllers/bookings_controller.rb
app/views/bookings/show.html.erb

booking-page

---

app/views/bookings/show.html.erb

booking page

---

app/models/review.rb
app/views/clients/show.html.erb

ticket-update

---

app/controllers/reviews_controller.rb
app/models/booking.rb
app/views/reviews/index.html.erb
app/views/shared/_reviews_index.html.erb

index-reviews-incomplete

---

app/controllers/reviews_controller.rb
app/views/reviews/index.html.erb

changes-random

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/index.html.erb
app/views/bookings/new.html.erb

fix-creation-booking

---

app/views/bookings/index.html.erb
app/views/reviews/new.html.erb

front-end-times-reviews-conditional
ATTENTION: 
NEW REVIEW not working (but working) because the if statement is not working

front-end-times-reviews-conditional

---

app/views/clients/index.html.erb
app/views/shared/_navbar.html.erb

fix-errors

---

app/controllers/reviews_controller.rb
app/views/layouts/application.html.erb

small-fixes

---

app/assets/stylesheets/components/_card_index.scss
app/views/clients/_search_clients.html.erb

small-fixes-2

---

app/controllers/reviews_controller.rb
app/views/clients/_search_clients.html.erb
app/views/clients/show.html.erb

CCR score calculation improvement 
Multiplications

ccr-improvement

---

app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb

index - order desc
ccr round(1)

index-order

---

app/views/shared/_list.html.erb

fix-index-new-1

---

app/assets/stylesheets/pages/_home.scss
app/views/clients/_search_clients.html.erb
app/views/clients/index.html.erb
app/views/shared/_list.html.erb

add create button to pages index

add create button to pages index

---

app/controllers/bookings_controller.rb
app/views/bookings/edit.html.erb

update booking working  is working now

update booking working

---

app/assets/stylesheets/components/_card_index.scss
app/assets/stylesheets/components/_card_show.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_reviews_container.scss
app/assets/stylesheets/pages/_client_show.scss
app/assets/stylesheets/pages/_index.scss
app/views/clients/show.html.erb

show-client

---

app/controllers/bookings_controller.rb
app/views/bookings/show.html.erb

show-booking

---

app/assets/stylesheets/components/_alert.scss
app/javascript/controllers/alert_controller.js
app/views/shared/_list.html.erb

sweet-alert-fix

---

app/views/layouts/application.html.erb
app/views/reviews/show.html.erb

footer related fix

---

app/controllers/bookings_controller.rb
app/javascript/controllers/countdown_controller.js
app/models/booking.rb
app/views/bookings/without_reviews.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

pendig reviews

---

db/seeds.rb

herique book

---

app/assets/stylesheets/components/_alert.scss
app/controllers/clients_controller.rb
app/javascript/controllers/alert_controller.js
app/models/client.rb

Final fix client create

---

app/javascript/controllers/countdown_controller.js
app/models/booking.rb
app/views/bookings/_newBooking.html.erb
app/views/bookings/without_reviews.html.erb

count update

---

app/views/bookings/without_reviews.html.erb
app/views/clients/show.html.erb
app/views/reviews/pendig_reviews.erb
app/views/shared/_footer.html.erb

client-show-review-changes

---

app/assets/stylesheets/pages/_home.scss
app/views/clients/_search_clients.html.erb
app/views/clients/index.html.erb
app/views/shared/_list.html.erb

no more containers

---

app/javascript/controllers/alert_controller.js
app/models/review.rb
app/views/clients/_search_clients.html.erb
app/views/shared/_navbar.html.erb

a-lot-changed

---

app/assets/stylesheets/pages/_home.scss

container-update

---

app/controllers/clients_controller.rb
app/javascript/controllers/alert_controller.js
app/views/bookings/_newBooking.html.erb
app/views/bookings/new.html.erb
app/views/clients/_newClient.html.erb
app/views/clients/new.html.erb

booking redirect fix

---

app/views/bookings/show.html.erb

show booking

---

app/javascript/controllers/alert_controller.js
app/views/clients/_newClient.html.erb

new changes

---

app/views/layouts/application.html.erb

fav icon fix

---

db/seeds.rb

seed demo fix
